SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `globals` (
  `id` INT NOT NULL,
  `key` VARCHAR(255) NOT NULL,
  `value` TEXT NULL DEFAULT NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

ALTER TABLE `globals`
  ADD PRIMARY KEY (`id`)
  ADD UNIQUE INDEX `key` (`key` ASC) VISIBLE;

ALTER TABLE `globals`
  MODIFY `id` INT NOT NULL AUTO_INCREMENT;

COMMIT;