# ZRPS (ZombsRoyale Private Server) API Config File

# Database Connection Information
[database]
host = "localhost"
port = 3306
user = "root"
password = ""
database_name = "zrps"

# Server Settings
[server]
name = "Example ZRPS"
port = 3001
cookie_secret = "my-secret"
hcaptcha_site_key = "10000000-ffff-ffff-ffff-000000000001"
hcaptcha_secret_key = "0x0000000000000000000000000000000000000000"